name: singularity
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.05.10
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - fsspec
  - graphviz
  - hvplot
  - intake-esm
  - jupyter-server-proxy
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - python-graphviz
  - scipy
  - xarray
  - zarr
