name: singularity
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - fsspec
  - geoviews
  - holoviews
  - hvplot
  - intake
  - jupyter-server-proxy
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - pytest
  - python-blosc
  - scipy
  - xarray
  - zarr
