name: singularity
channels:
  - conda-forge
dependencies:
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - fsspec
  - graphviz
  - intake-esm
  - jupyter-server-proxy
  - matplotlib
  - netcdf4
  - pandas
  - scipy
  - xarray
  - zarr
